#+ endpoint: http://10.5.27.50:7200/sparql
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX org-lab: <http://purl.org/zhejianglab/irobot-center/ontologies/org-lab#>
select distinct ?orgname where {
    ?project foaf:name "深海软体机器智能驱动技术";
             org:hasMember ?person.
    ?org org:hasMember ?person;
         a org-lab:NonprofitEntity;
         foaf:name ?orgname.
}
